name: deploy

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@prerelease/v4

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@prerelease/v4

      - name: Publish
        run: >-
          ./gradlew publishPlugins -s
            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
